#!/bin/bash
for f in ??.txt
do
	cat $f | awk -f ../splitletters.awk | sed -r "s/   / <SPACE> /g" > R$f

	head -n 10000 R$f > Rtrain.${f%.txt}
	tail -n 10000 R$f > Rtest.${f%.txt}

	ngram-count -order 3 -text Rtrain.${f%.txt} -write R${f%.txt}3g.bo -write-vocab R${f%.txt}.voc
	ngram-count -read R${f%.txt}3g.bo -lm R${f%.txt}3g.BO -gt2min 1 -gt3min 2
done