#!/bin/bash
for f in ??.txt
do
	cat $f | awk -f ../splitletters.awk > S$f

	head -n 10000 S$f > Strain.${f%.txt}
  	tail -n 10000 S$f > Stest.${f%.txt}

	ngram-count -order 3 -text Strain.${f%.txt} -write S${f%.txt}3g.bo -write-vocab S${f%.txt}.voc
  	ngram-count -read S${f%.txt}3g.bo -lm S${f%.txt}3g.BO -gt2min 1 -gt3min 2
done