# CHEMINS
data: /home/xia/Projects/INFO4/CL/TP/5/BTEC-en-fr/BTEC-en-fr
save_model: /home/xia/Projects/INFO4/CL/TP/5/BTEC-en-fr/vanilla/rnn-basic

# ENCODEUR - DECODEUR
encoder_type: brnn
enc_layers: 1
dec_layers: 1

rnn_type: LSTM
dec_rnn_size: 128
enc_rnn_size: 128

# ATTENTION
global_attention: none

# BATCH
batch_size: 32

# STEPS
save_checkpoint_steps: 625
train_steps: 2000
valid_steps: 625

# GPU (à décommenter si vous voulez utiliser votre carte graphique)
#world_size: 1
#gpu_ranks:
#- 0

# LOG & TENSORBOARD
report_every: 20
log_file: /home/xia/Projects/INFO4/CL/TP/5/BTEC-en-fr/vanilla/rnn-basic.log
#tensorboard: 'true'
#tensorboard_log_dir: data/en-fr_TP/tensorboard_log
