---
title: "TD4"
author: "Mica"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercice 1. Générateurs à base de congruences

Générateur : $x_{n+1} = ax_n \text{ mod } 7$.

```{r exo1}
suite <- function(n, a, s1) {
  s = rep(-1, n)
  s[1] = s1
  for (i in 2:n) {
    s[i] = (a * s[i-1]) %% 7
  }
  return(s)
}

# longueur max cycle : 6 ?
n = 100
a = 3
s1 = 1
suite(n, a, s1) # 1 3 2 6 4 5 : longueur 6
a = 4
suite(n, a, s1) # 1 4 2 : longueur 3
# suite(rep(n, 5), 1:5, rep(s1, 5))
```

## Exercice 2. Période d'un générateur à base de congruences

Suite : $x_{n+1} = ax_n + b \text{ mod } m$.

Cycle maximal si les trois hypothèses sont vérifiées :

1. $PGCD(a, m) = 1, PGCD(b, m) = 1$,
2. Si un nombre premier $p$ divise $m$, alors $p$ divise $a-1$,
3. Si $4$ divise $m$, alors $4$ divise $a-1$.

```{r exo2-1}
suite <- function(a, b, m, s1) {
  s = rep(-1, n)
  s[1] = s1
  for (i in 2:n) {
    s[i] = (a * s[i-1] + b) %% m
  }
  return(s)
}

gcd <- function(x,y) {
  r <- x %% y;
  return(ifelse(r, gcd(y, r), y))
}

s1 = 1
a = 4; b = 2; m = 9; suite(a, b, m, s1) # OK : cycle 9
a = 2; b = 2; m = 9; suite(a, b, m, s1) # KO : 3 % 9 == 0 or 3 % (2 - 1) != 0
a = 3; b = 3; m = 9; suite(a, b, m, s1) # KO : PGCD(3, 9) = 3 or 3 != 1
a = 1; b = 1; m = 9; suite(a, b, m, s1) # OK : cycle 9
```

```{r exo2-2}
s1 = suite(11, 1, 71, 1)
# montrer que la période de s est 70 (utiliser which)
which(s1==1)
hist(s1)

s2 = suite(24298, 99991, 199017, 1)
hist(s2)
```